image: golang:latest

before_script:
  - cmd/build

test:
  script:
  - cmd/test
  - cmd/coverage

  artifacts:
    paths:
      - public/
  coverage: '/^total:[\t ]*\(statements\)[\t ]*\d+.\d+\%$/'


