sudo: required

language: go

services:
- docker

before_install:
- docker pull golang:latest

script:
- docker run --rm -v $(pwd):/app -w /app golang:latest bash -c "make distclean; make"
- docker run --rm -v $(pwd):/app -w /app golang:latest bash -c "make testclean; make test"
