version: 2
jobs:
  build:
    docker:
    - image: golang:latest
    steps:
    - checkout
    - run: cmd/build

  test:
    docker:
    - image: golang:latest
    steps:
    - checkout
    - run: cmd/test
    - run: cmd/coverage

workflows:
  version: 2
  build_and_test:
    jobs:
    - build
    - test
